version: "3"
services:
  monapp:
    build: .
    image: elbissat/monapp
    depends_on:
      - redis
    ports:
      - "8585:80"
    networks:
      - monreseau
    environment:
      - NOM=Ayouris
  redis:
    image: redis
    networks:
      - monreseau

networks:
  monreseau:
